# Generated by Django 5.0 on 2024-01-03 13:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='followed_by',
            field=models.ManyToManyField(related_name='followed_topics', to=settings.AUTH_USER_MODEL),
        ),
    ]
