# Generated by Django 5.0 on 2024-01-07 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_topic_topic_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='questions',
        ),
    ]
