# Generated by Django 5.0.1 on 2024-03-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_remove_topic_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="popularty",
            field=models.IntegerField(default=0),
        ),
    ]
