# Generated by Django 5.0.1 on 2024-04-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
